baseurl = "https://yanfei-wu.github.io/"
title = "Yanfei Wu"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = "yanfeiwu"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  description = "Describe your website"
  copyright = "&copy;2016 Yanfei Wu"
  sidebarAbout = [
    "This site is about my amazing journey in data science and machine learning. I am a Materials Science PhD transitioning into Data Science. I love analyzing interesting datasets, creating insightful visualizations, and building machine learning models.", 
    "Please feel free to contact me if you have any question or suggestion about my posts, or would like to hire me:)"
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "wuxxx728@umn.edu"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "Blogs"
  url = "post/"

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [params.social]
  email         = "wuxxx728@umn.edu"
  linkedin      = "https://www.linkedin.com/in/yanfei-wu-76696383/"
  github        = "https://github.com/yanfei-wu"

  [params.widgets]
   categories = false
   tags = true
   search = false
